import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {registerHooks} from 'node:module';
registerHooks({resolve(s,c,n){return s==='three'?{url:new URL('../dist/vendor/three.module.js',import.meta.url).href,shortCircuit:true}:n(s,c);}});
test('the published athlete asset is a skinned body with all named clips and valid bindings',async()=>{
 const {GLTFLoader}=await import('../dist/vendor/loaders/GLTFLoader.js');
 const b=await readFile(new URL('../dist/assets/athlete.glb',import.meta.url));
 const gltf=await new GLTFLoader().parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'');
 const surface=gltf.scene.getObjectByName('AthleteSurface'),meshes=[];surface?.traverse(o=>{if(o.isSkinnedMesh)meshes.push(o);});const mesh=meshes[0];
 assert.ok(mesh?.isSkinnedMesh,'athlete must deform with a skeleton');
 const {allIds}=await import('../dist/exercises.js');
 assert.equal(gltf.animations.length,allIds.length);
 assert.ok(mesh.skeleton.bones.some(b=>b.name==='Neck'));
 assert.ok(mesh.skeleton.bones.some(b=>b.name==='R_Index1'));
 const weight=mesh.geometry.getAttribute('skinWeight');
 for(let i=0;i<weight.count;i++)assert.ok(Math.abs(weight.getX(i)+weight.getY(i)+weight.getZ(i)+weight.getW(i)-1)<1e-5);
 assert.deepEqual([...new Set(meshes.map(m=>m.material.name))].sort(),['Body','FocusChest','Outfit']);
 const index=mesh.geometry.getAttribute('skinIndex'),bones=mesh.skeleton.bones.length;
 for(let i=0;i<index.count;i++)for(let k=0;k<4;k++)assert.ok(index.getComponent(i,k)<bones,'skin index within skeleton');
 for(const m of meshes)assert.ok(m.geometry.index.count>0&&m.geometry.getAttribute('uv'),'textured primitives');
});
